name: riverpod_iap
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  in_app_purchase: ^3.0.7
  flutter_riverpod: ^1.0.4
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.0.3
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.10
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true
